export const MOBILE_CONSTANTS = {
  RIDGES_BETWEEN_POINTS: 1,
  RIDGE_HEIGHT: 5,
  PATH_COUNT: 20,
  VIEWBOX_HEIGHT: 800,
  VIEWBOX_WIDTH: 1440,
};

export const MOBILE_PORTRAIT_CONSTANTS = {
  RIDGES_BETWEEN_POINTS: 1,
  RIDGE_HEIGHT: 10,
  PATH_COUNT: 50,
  VIEWBOX_HEIGHT: 1440,
  VIEWBOX_WIDTH: 800,
};

